name = "corisa-ai"
compatibility_date = "2025-07-27"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "npm run build"

# Environment variables (if needed)
[vars]
NODE_ENV = "production"