name = "corisa-ai"
compatibility_date = "2025-07-27"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables
[vars]
NODE_ENV = "production"
# Set this in Cloudflare Pages project settings
OPENAI_API_KEY = ""